site_name: 生物信息最差实践
site_description: '最差也能实践'
site_author: 'pzweuj'
site_url: 'https://pzweuj.github.io/worstpractice'
theme: 
  name: 'material'
copyright: 'Copyright &copy; 2019 pzweuj'

repo_url: https://github.com/pzweuj/pzweuj.github.io/

extra:
  palette:
    primary: 'light blue'

nav:
  - '前言': index.md

use_directory_urls: true

extra_javascript:
  #- https://cdn.rawgit.com/knsv/mermaid/6.0.0/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js
  - assets/js/umlconvert.js

google_analytics: ['UA-131202162-1', 'auto']