markdown: kramdown
highlighter: rouge
safe: false
lsi: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 生物信息文件夹
url: pzweuj.github.io
desc: 得闲吞POT

custom:
    category:
        default: 默认
        biology: 生物相关
        coding: 编程相关
        database: 数据库
        software: 软件
    categories:
      - name:  default
        title: 默认
        
      - name:  biology
        title: 生物相关
        
      - name:  coding
        title: 编程相关
        
      - name:  database
        title: 数据库
        
      - name:  software
        title: 软件

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: pzweuj
        email: pzweuj@live.com
        disqus:                # Disqus缩略标识
        gcse:  # Google自定义搜索标识ID
        github: pzweuj                 # GitHub账号
        gravatar:   #Gravatar头像标识
        stackoverflow: 
        weibo:
        instagram: 

    disqus: # Disqus评论的JS地址
    gapi:   # Google API地址
    gravatar: # Gravatar头像服务器地址
